// SPDX-License-Identifier: Apache-2.0
/**
 * Copyright (C) 2024 Jijoong Moon <jijoong.moon@samsung.com>
 *
 * @file    context_data.h
 * @date    04 April 2026
 * @see     https://github.com/nntrainer/nntrainer
 * @author  Jijoong Moon <jijoong.moon@samsung.com>
 * @bug     No known bugs except for NYI items
 * @brief   ContextData — lightweight container shared between Context and
 *          RunLayerContext. Separated from context.h to avoid circular
 *          dependencies (context.h → layer_devel.h → layer_context.h).
 */

#ifndef __CONTEXT_DATA_H__
#define __CONTEXT_DATA_H__

#include <mem_allocator.h>
#include <memory>

namespace nntrainer {

class ComputeOps;

/**
 * @class ContextData contains Data which generated by Context to use in Layers
 * created by Context
 * @brief Container to hold context data generated by Context. Eventually
 * RunLayerContext in layer_node will hold the ContextData, so that, Layer can
 * access this Context Data.
 */
class ContextData {
public:
  ContextData() = default;
  virtual ~ContextData() = default;

  /**
   * @brief Get the backend type name for this context data.
   *
   * Override in subclasses to identify the backend type.
   * Used for type checking and debugging.
   *
   * @return const char* backend type name (e.g., "cpu", "gpu", "qnn")
   */
  virtual const char *getType() const { return "cpu"; }

  /**
   * @brief Type-safe downcast to a specific ContextData subclass.
   *
   * Use this instead of static_pointer_cast to safely access
   * vendor-specific data. Returns nullptr if the type doesn't match.
   *
   * Example:
   *   auto *qnn = context.getContextData()->as<QNNBackendVar>();
   *   if (!qnn) throw std::runtime_error("not a QNN context");
   *
   * @tparam T target ContextData subclass type
   * @return T* pointer to the subclass, or nullptr if wrong type
   */
  template <typename T> T *as() { return dynamic_cast<T *>(this); }

  template <typename T> const T *as() const {
    return dynamic_cast<const T *>(this);
  }

  std::shared_ptr<MemAllocator> getMemAllocator() { return mem_allocator; }

  void setMemAllocator(std::shared_ptr<MemAllocator> m) { mem_allocator = m; }

  /**
   * @brief Get the compute ops table for this context
   * @return ComputeOps* pointer to the ops table, or nullptr if not set
   */
  ComputeOps *getComputeOps() { return compute_ops; }

  /**
   * @brief Set the compute ops table for this context
   * @param ops pointer to the ops table
   */
  void setComputeOps(ComputeOps *ops) { compute_ops = ops; }

private:
  std::shared_ptr<MemAllocator> mem_allocator = nullptr;
  ComputeOps *compute_ops = nullptr;
};

} // namespace nntrainer

#endif // __CONTEXT_DATA_H__
