// SPDX-License-Identifier: Apache-2.0
/**
 * Copyright (C) 2026 Samsung Electronics Co., Ltd. All Rights Reserved.
 *
 * @file   unittest_causallm_qwen2_reference.cpp
 * @date   15 June 2026
 * @brief  Differential (cross-validation) tests for the tiny Qwen2 model.
 *
 * Compares nntrainer's Qwen2 output against golden fixtures generated by
 * HuggingFace transformers (generate_qwen2_reference.py). The generic checks
 * live in causallm_test_utils; this file only binds the Qwen2 adapter and the
 * fixture name. Tests skip automatically when fixtures or the nntr_quantize
 * binary are absent.
 *
 * @see    https://github.com/nntrainer/nntrainer
 * @author Jungwon Lee <jungone.lee@samsung.com>
 * @bug    No known bugs except for NYI items
 */

#include <causallm_test_utils.h>

#include <gtest/gtest.h>

#include <qwen2_causallm.h>

#include <memory>

namespace {

/**
 * @brief Differential model descriptor for the tiny Qwen2 fixture
 */
causallm_test::DifferentialModel qwen2Model() {
  return {
    "qwen2_tiny",
    [](causallm::json &cfg, causallm::json &gen_cfg, causallm::json &nntr_cfg) {
      return std::make_unique<
        causallm_test::CausalLMTestAdapter<causallm::Qwen2CausalLM>>(
        cfg, gen_cfg, nntr_cfg);
    },
  };
}

/**
 * @brief FP32 prefill logits and greedy tokens match the HF reference
 */
TEST(Qwen2DifferentialTest, FP32MatchesHFReference) {
  causallm_test::runFp32DifferentialChecks(qwen2Model());
}

/**
 * @brief Q4_0 quantized logits stay within tolerance of the FP32 reference
 */
TEST(Qwen2DifferentialTest, Q40CloseToFP32Reference) {
  causallm_test::runQ40DifferentialChecks(qwen2Model());
}

} // namespace
