// SPDX-License-Identifier: Apache-2.0
/**
 * Copyright (C) 2026 Samsung Electronics Co., Ltd. All Rights Reserved.
 *
 * @file   unittest_causallm_qwen3_moe_reference.cpp
 * @date   15 June 2026
 * @brief  Differential (cross-validation) tests for the tiny Qwen3MoE model.
 *
 * Compares nntrainer's Qwen3MoE output against golden fixtures generated by
 * HuggingFace transformers (generate_qwen3_moe_reference.py). The generic
 * checks live in causallm_test_utils; this file only binds the Qwen3MoE
 * adapter and the fixture name. Tests skip automatically when fixtures or the
 * nntr_quantize binary are absent.
 *
 * Note: Q4_0 quantization is not tested here because the MoE router gate
 * weight has shape [hidden, num_experts] with num_experts=4, which is not
 * divisible by 32 and therefore cannot be Q4_0-quantized.
 *
 * @see    https://github.com/nntrainer/nntrainer
 * @author Jungwon Lee <jungone.lee@samsung.com>
 * @bug    No known bugs except for NYI items
 */

#include <causallm_test_utils.h>

#include <gtest/gtest.h>

#include <qwen3_moe_causallm.h>

#include <memory>

namespace {

/**
 * @brief Differential model descriptor for the tiny Qwen3MoE fixture
 */
causallm_test::DifferentialModel qwen3MoeModel() {
  return {
    "qwen3_moe_tiny",
    [](causallm::json &cfg, causallm::json &gen_cfg, causallm::json &nntr_cfg) {
      return std::make_unique<
        causallm_test::CausalLMTestAdapter<causallm::Qwen3MoECausalLM>>(
        cfg, gen_cfg, nntr_cfg);
    },
  };
}

/**
 * @brief FP32 prefill logits and greedy tokens match the HF reference
 */
TEST(Qwen3MoeDifferentialTest, FP32MatchesHFReference) {
  causallm_test::runFp32DifferentialChecks(qwen3MoeModel());
}

} // namespace
