// SPDX-License-Identifier: Apache-2.0
/**
 * Copyright (C) 2026 Samsung Electronics Co., Ltd. All Rights Reserved.
 *
 * @file   unittest_causallm_tinybert_reference.cpp
 * @date   16 June 2026
 * @brief  Differential test for the tiny MultilingualTinyBert encoder.
 *
 * Compares nntrainer's BERT encoder output (raw, unpooled last hidden state)
 * against a golden fixture from HuggingFace BertModel
 * (generate_tinybert_reference.py). The reference is the full [seq_len, hidden]
 * hidden state flattened row-major, since the nntrainer BERT path performs no
 * pooling. MultilingualTinyBert sanitizes its config in the constructor, so a
 * thin subclass owns the (virtual) Transformer mem-initializer.
 *
 * Guarded for Linux/non-Android only, matching the factory registration in
 * Applications/CausalLM/main.cpp. The test skips when the fixture is absent.
 *
 * The tinybert_tiny fixture is generated by generate_tinybert_reference.py and
 * committed alongside this file. The previous NaN issue (mha_core.cpp key cache
 * corrupted by RoPE with theta=0) was fixed by setting use_rope=false in
 * bert_transformer.cpp::createAttention().
 *
 * @see    https://github.com/nntrainer/nntrainer
 * @author Jungwon Lee <jungone.lee@samsung.com>
 * @bug    No known bugs except for NYI items
 */

#include <gtest/gtest.h>

#if !defined(_WIN32) && !defined(__ANDROID__)

#include <causallm_test_utils.h>

#include <multilingual_tinybert_16mb.h>

#include <memory>

namespace {

/**
 * @brief Tiny MultilingualTinyBert differential adapter
 *
 * BertTransformer sanitizes its config before initializing the virtual
 * Transformer base, so this thin subclass owns that mem-initializer.
 */
class TinyBertRefAdapter final
  : public causallm_test::EmbeddingTestAdapter<causallm::MultilingualTinyBert> {
public:
  TinyBertRefAdapter(causallm::json &cfg, causallm::json &generation_cfg,
                     causallm::json &nntr_cfg) :
    causallm::Transformer(sanitizeConfig(cfg), generation_cfg, nntr_cfg,
                          causallm::ModelType::EMBEDDING),
    causallm_test::EmbeddingTestAdapter<causallm::MultilingualTinyBert>(
      cfg, generation_cfg, nntr_cfg) {}
};

/**
 * @brief Differential model descriptor for the tiny MultilingualTinyBert
 * fixture
 */
causallm_test::DifferentialModel tinyBertModel() {
  return {
    "tinybert_tiny",
    [](causallm::json &cfg, causallm::json &gen_cfg, causallm::json &nntr_cfg) {
      return std::make_unique<TinyBertRefAdapter>(cfg, gen_cfg, nntr_cfg);
    },
  };
}

/**
 * @brief FP32 raw encoder output matches the HF BertModel reference
 */
TEST(TinyBertDifferentialTest, FP32MatchesHFReference) {
  causallm_test::runFp32EmbeddingDifferentialChecks(tinyBertModel());
}

/**
 * @brief Q4_0 encoder output is close to the HF FP32 reference
 *        (skips automatically if nntr_quantize does not support
 * BertForMaskedLM)
 */
TEST(TinyBertDifferentialTest, Q40CloseToFP32Reference) {
  causallm_test::runQ40EmbeddingDifferentialChecks(tinyBertModel());
}

} // namespace

#endif // !_WIN32 && !__ANDROID__
