// SPDX-License-Identifier: Apache-2.0
/**
 * Copyright (C) 2026 Seunghui Lee <shsh1004.lee@samsung.com>
 *
 * @brief  Embedded DDTree buildTree golden vectors (auto-generated)
 * @file   build_golden.h
 * @date   05 June 2026
 * @see    https://github.com/nntrainer/nntrainer
 * @author Seunghui Lee <shsh1004.lee@samsung.com>
 * @bug    No known bugs except for NYI items
 *
 * Generated by gen_golden.py -- do not edit by hand. Regenerate with
 * `python3 gen_golden.py`. Format documented above in gen_golden.py.
 */
#ifndef __NNTRAINER_DDTREE_BUILD_GOLDEN_H__
#define __NNTRAINER_DDTREE_BUILD_GOLDEN_H__

static const char *const kDDTreeBuildGolden = R"GOLDEN(
NCASES 4
CASE small
DIMS 2 3 3
LOGITS 2.0 1.0 0.0 0.0 -1.0 1.0
NODES 3 0 2 1
DEPTHS 3 1 2 1
PARENTS 4 -1 0 1 0
VIS 4 1 0 0 0 1 1 0 0 1 1 1 0 1 0 0 1
CASE tie
DIMS 2 3 4
LOGITS 1.0 1.0 0.0 0.5 0.5 0.5
NODES 4 0 1 2 0
DEPTHS 4 1 1 1 2
PARENTS 5 -1 0 0 0 1
VIS 5 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 1
CASE budget_gt_vocab
DIMS 2 3 100
LOGITS 8.0 5.0 2.0 6.0 5.0 4.0
NODES 12 0 0 1 2 1 0 1 2 2 0 1 2
DEPTHS 12 1 2 2 2 1 2 2 2 1 2 2 2
PARENTS 13 -1 0 1 1 1 0 5 5 5 0 9 9 9
VIS 13 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1
CASE full_fill
DIMS 3 4 8
LOGITS 3.0 2.0 1.0 0.0 3.0 2.0 1.0 0.0 3.0 2.0 1.0 0.0
NODES 8 0 0 0 1 1 0 1 0
DEPTHS 8 1 2 3 1 2 2 3 3
PARENTS 9 -1 0 1 2 0 1 4 2 5
VIS 9 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1
)GOLDEN";

#endif // __NNTRAINER_DDTREE_BUILD_GOLDEN_H__
